# Generated by Django 3.2 on 2023-07-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_auto_20230427_0656'),
        ('profiles', '0002_auto_20230402_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_by', to='tweets.Tweet'),
        ),
    ]
